[package]
name = "credx"
version = "0.1.0"
edition = "2021"


[dependencies]
hex = "0.4"
merlin = "3"
rand = "0.8"
rand_core = "0.6"
regex = "1"
yeti = { version = "0.2", path = "../yeti" }
serde = { version = "1", features = ["serde_derive"] }
serde_regex = "1"
