[package]
name = "credx"
version = "0.1.0"
edition = "2021"


[dependencies]
bulletproofs = { version = "4.0.0", path = "../bulletproofs" }
group = "0.10"
hex = "0.4"
maplit = "1"
merlin = "3"
rand = "0.8"
rand_core = "0.6"
regex = "1"
yeti = { version = "0.2", path = "../yeti" }
serde = { version = "1", features = ["serde_derive"] }
serde_bare = "0.5"
serde_json = "1"
serde_regex = "1"
serde_repr = "0.1"
uint-zigzag = { version = "0.2", features = ["std"] }

[dev-dependencies]
serde_cbor = "0.11"
sha2 = "0.9"
